packages:
  - artifacts/*
  - lib/*

allowBuilds:
  esbuild: true
  '@swc/core': true

autoInstallPeers: false

catalog:
  '@types/node': ^24.13.2
  drizzle-orm: ^0.45.2
  zod: 3.25.76

onlyBuiltDependencies:
  - esbuild
  - '@swc/core'
